### ISSUE TITLE
typo on default validation options 

### ISSUE THREAD

**Issue by guanglinlv** [cdbattags/lua-resty-jwt#14]
Hi

is it a typo ? `exp` and `nbf` never defined. see [L359](https://github.com/cdbattags/lua-resty-jwt/blob/master/lib/resty/jwt.lua#L359)

**Comment by cdbattags** [comment]
Should be working as intended. Those keys should always exist in your JWT, no?

**Comment by guanglinlv** [comment]
I did the following change, it works as expect IMO.

```lua
function _M.get_default_validation_options(self, jwt_obj)
  return {
    [str_const.require_exp_claim]=jwt_obj[str_const.payload][str_const.exp] ~= nil,
    [str_const.require_nbf_claim]=jwt_obj[str_const.payload][str_const.nbf] ~= nil
  }
end
```

**Comment by acerveaux** [comment]
Is there any PR planned to fix this ? 
Thanks in advance.

**Comment by cdbattags** [comment]
@guanglinlv, want to put in a PR for this?
