### ISSUE TITLE
new release based on master branch

### ISSUE THREAD

**Issue by vinayakhulawale** [cdbattags/lua-resty-jwt#21]
@cdbattags - Is it possible to release next version from current master and publish in luarocks repo ?

**Comment by cdbattags** [comment]
Sure thing. I'll have a new slice for ya by Wednesday end of day.

There were a couple changes to the test suite that I want to be sure are working properly.

**Comment by cdbattags** [comment]
new release here https://github.com/cdbattags/lua-resty-jwt/releases/tag/v0.2.1

will publish to LuaRocks and OPM next week
