### ISSUE TITLE
The latest version (v0.2.1) can't be installed via luarocks

### ISSUE THREAD

**Issue by spacewander** [cdbattags/lua-resty-jwt#23]
The latest version which can be install via luarocks is still v0.2.0. See https://luarocks.org/modules/cdbattags/lua-resty-jwt

**Comment by alexandrim0** [comment]
I`m voting for opm also.

**Comment by alexandrim0** [comment]
@cdbattags 
Hello!
Would you publish latest version to OPM or luarocks in march or there is some trouble?

**Comment by cdbattags** [comment]
Will be sure to do tonight after the day job.

I was waiting on #26. Now that that's in, I'll cut a `v0.2.2` and then publish that and `v0.2.1` both to LuaRocks and OPM.

**Comment by cdbattags** [comment]
0.2.1 and 0.2.2 are both now released on LuaRocks! OPM is a little bit trickier with the new submodule implementation but hope to have it done by tomorrow EOD.

**Comment by alexandrim0** [comment]
Great!
Thank you!
But how long is a day on your planet? ;-)

**Comment by cdbattags** [comment]
This ticket is done as far as the original ask goes. If anyone else would like to step up as a sub-maintainer I'd love the help!

I'm a maintainer/contributor of ~3 projects now along with a day job and a few other hobbies 😉

I know many people rely on this project but I also know that if you have an OpenResty infrastructure/setup in your stack you should know how to use git releases in place of LuaRocks/OPM

**Comment by cdbattags** [comment]
OPM is by far one of the worst package manager ecosystems I've seen but more power to them for trying to carve their own path

**Comment by alexandrim0** [comment]
OK.
You are right, I will go that way (luarocks).
Thank you, again!
