### ISSUE TITLE
The latest 2 versions (v0.2.1 and v0.2.2) can't be installed via OPM

### ISSUE THREAD

**Issue by cdbattags** [cdbattags/lua-resty-jwt#27]
See title!

**Comment by hroost** [comment]
Hi, thanks for maintaining this repo!

Are you planning to update this package at OPM? or what is needed for this?

**Comment by cdbattags** [comment]
I've deprecated the OPM upload in favor of LuaRocks for now! Sorry!

**Comment by ruhrohraggy** [comment]
@cdbattags Any particular reason? Considering OpenResty (where I would assume this is being used in the majority of cases) suggests the use of OPM rather than LuaRocks, I'd think it'd be valuable to keep pushing to both
