### ISSUE TITLE
Error: Rockspec format 3.0 is not supported, please upgrade LuaRocks.

### ISSUE THREAD

**Issue by Ostico** [cdbattags/lua-resty-jwt#28]
These are the the os/server/package info. Tell me if you need more info.

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

# apt-cache policy luarocks
luarocks:
  Installed: 2.4.2+dfsg-1
  Candidate: 2.4.2+dfsg-1
  Version table:
 *** 2.4.2+dfsg-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status

# luarocks install lua-resty-jwt
Installing https://luarocks.org/lua-resty-jwt-0.2.2-0.src.rock

Error: Rockspec format 3.0 is not supported, please upgrade LuaRocks.
```

**Comment by Ostico** [comment]
I tried with a fallback, this installation works:
```
luarocks install lua-resty-jwt 0.2.0
```

**Comment by Ostico** [comment]
hmac installed by luarocks was in conflict with the one in this package.
I removed the luarock package.
Now it works 👍

**Comment by cdbattags** [comment]
@Ostico sounds like you're all set?

Closing now. If you need anything else please feel free to reach out!

**Comment by peterDitrih** [comment]
> hmac installed by luarocks was in conflict with the one in this package. I removed the luarock package. Now it works +1

hi can u tell me more about the solution to this problem?

**Comment by peterDitrih** [comment]
@Ostico ?

**Comment by Ostico** [comment]
Hi @peterDitrih 

this version 
```
luarocks install lua-resty-jwt 0.2.0
```
works with
```
luarocks: 2.4.2+dfsg-1
```

**Comment by peterDitrih** [comment]
> Hi @peterDitrih
> 
> this version
> 
> ```
> luarocks install lua-resty-jwt 0.2.0
> ```
> 
> works with
> 
> ```
> luarocks: 2.4.2+dfsg-1
> ```
do you mean you couldn’t customize version 0.2.3?

**Comment by peterDitrih** [comment]
`root@peter-dell:/# luarocks install lua-resty-jwt
Installing https://luarocks.org/lua-resty-jwt-0.2.3-0.src.rock

Error: Rockspec format 3.0 is not supported, please upgrade LuaRocks.
root@peter-dell:/# 
`
I just have the same problem and i couldn't resolve it (0.2.0 is working, but maybe i could install last version? :) )
