### ISSUE TITLE
update tests for 1.13.6.2

### ISSUE THREAD

**Issue by cdbattags** [cdbattags/lua-resty-jwt#3]
@cybrq-as, mind helping me out here when you get a chance? See failing build on Travis:

https://travis-ci.org/cdbattags/lua-resty-jwt/builds/386418835

Again, sorry for doing this on master. Should reach stability in a couple days and do things PR only.

**Comment by cdbattags** [comment]
Ope... Wut, it looks like the response is just out of order?

**Comment by cybrq-as** [comment]
Could be an updated module. The real fix is usually to order the JSON keys.

**Comment by mikz** [comment]
We are quite successfully running big test suite in parallel on CircleCI (https://circleci.com/gh/3scale/apicast).

Also we are maintaining OpenResty docker images with luarocks/prove support: https://github.com/3scale/s2i-openresty/releases

Let me know if you want some help getting CI to a good shape. Right now it is using docker image with old OpenResty to run all the tests, so not really practical as it does not test the OpenSSL 1.1.

**Comment by cdbattags** [comment]
Fixed this with https://github.com/cdbattags/lua-resty-jwt/commit/21edb9b371828711b1b6b45698eead9681c6b7ca! Thanks so much! Would you mind possibly adding any other tests you can think of and opening a PR?
