### ISSUE TITLE
version0.2.2 also have size of C type is unknown or too large at line 39

### ISSUE THREAD

**Issue by Michael-LiK** [cdbattags/lua-resty-jwt#30]
i use the sign rs256 meet the problem:
ERROR: /usr/local/openresty/lualib/resty/hmac.lua:105: size of C type is unknown or too large at line 39
stack traceback:
        /usr/local/openresty/lualib/resty/hmac.lua:105: in main chunk
        [C]: in function 'require'
        /usr/local/openresty/lualib/resty/jwt.lua:5: in main chunk
        [C]: in function 'require'
        jwt.lua:4: in function 'file_gen'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>
        [C]: in function 'xpcall'
        init_worker_by_lua:52: in function <init_worker_by_lua:50>

**Comment by cdbattags** [comment]
Do you have a minimal breaking example? Feel free to use the testing suite and put up a PR for the failing test for us to fix.

**Comment by fffonion** [comment]
Related to https://github.com/jkeys089/lua-resty-hmac/issues/19

**Comment by Michael-LiK** [comment]
thanks for your help, fffonion sovle my first problem ，the hs265 can use ,but rs256 is also wrong。

**Comment by cdbattags** [comment]
Why close? Did you solve this? Would you mind giving more context for others that might have similar issues?

**Comment by Michael-LiK** [comment]
i didn't sovle the problem ， i just use the evp.lua to create a signature by myself.

**Comment by Michael-LiK** [comment]
sorry, i think use the lib with wrong ways, the signature key i use it wrong.
