### ISSUE TITLE
JWE Signing lua entry thread aborted: runtime error: unknown reason

### ISSUE THREAD

**Issue by ernestclyde** [cdbattags/lua-resty-jwt#32]
Hello currently i am using openresty 1.15.8.3 and trying to sign JWE based on the example of 
[https://github.com/cdbattags/lua-resty-jwt#sign-jwe](url)

i got this error when signing JWE

`coroutine 0:
        [C]: in function 'error'
        /usr/local/openresty/site/lualib/resty/jwt.lua:202: in function 'derive_keys'
        /usr/local/openresty/site/lualib/resty/jwt.lua:407: in function 'sign'
        /app/clients/api/login.lua:84: in main chunk, client: xxx, server: xxx, request: "POST /api/login HTTP/1.1", host: "xxx", referrer: "xxx"
2020/05/12 09:05:57 [error] 23380#23380: *1 failed to load external Lua file "/app/clients/api/login.lua": /app/clients/api/login.lua:87: '}' expected near '=', client: xxx, server: xxx: "POST /api/login HTTP/1.1", host: "xxx", referrer: "xxx"`

**Comment by cdbattags** [comment]
have a code snippet? lua block to test?

**Comment by cdbattags** [comment]
@ernestclyde any update here? If not, I'll have to close this.

**Comment by LasithaPrabodha** [comment]
@cdbattags I also get this error.

`local cjson = require "cjson"
                        local jwt = require "resty.jwt"

                        local jwt_token = jwt:sign(
                                "lua-resty-jwt",
                                {
                                        header={typ="JWE", alg="dir", enc="A128CBC-HS256"},
                                        payload={foo="bar"}
                                }
                        )
                        ngx.say(jwt_token)
`

**Comment by cdbattags** [comment]
Feel free to go ahead and add a test to the `t` directory!

**Comment by cdbattags** [comment]
`A128CBC-HS256` was added for version 0.2.3! Feel free to check it out!
