### ISSUE TITLE
Dependencies do not match description

### ISSUE THREAD

**Issue by barrelmaker97** [cdbattags/lua-resty-jwt#37]
Recently installed this package via luarocks and realized that although this package depends on lua-resty-string and lua-resty-hmac, they're not actually listed in the dependencies in the rockspec file, so luarocks will install this package without verifying that the two dependencies are installed. Happy to make a PR to fix this, but I wanted to ask: what are the minimum acceptable versions of those dependencies?

**Comment by cdbattags** [comment]
I'm unsure about lua-resty-string but I know that I current bundle lua-resty-hmac with this "rock" as a submodule and an include on the spec.

**Comment by cdbattags** [comment]
"lua-resty-string" should be any version because very backwards compatible and just check out the commit hash for hmac. More than happy to have a PR for this! The luarocks environment I know is kinda funky
