### ISSUE TITLE
JWT tokens are different under different OpenResty versions

### ISSUE THREAD

**Issue by spacewander** [cdbattags/lua-resty-jwt#46]
Because the results of `cjson.encode` are different.
```lua
#!/usr/bin/env resty

local cjson = require("cjson")
print(cjson.encode({typ = "JWT", alg = "RS256"}))
```

Under OpenResty 1.17:
```
{"alg":"RS256","typ":"JWT"}
```

Under OpenResty 1.19:
```
{"typ":"JWT","alg":"RS256"}
```

**Comment by cdbattags** [comment]
I'm confused what the issue is here? Can you give a little more context?

**Comment by spacewander** [comment]
You can run this repo's test suite both under OpenResty 1.17 and under OpenResty 1.19, and then you will find the output is different.

**Comment by cdbattags** [comment]
I'm still confused because the internal lua data structure you're referring to is a table. I don't believe there are assurances to key order for these tables.

Is there a specific test that is breaking?

**Comment by vinayakhulawale** [comment]
I believe to maintain compatibility while verifying we need to make sure we use raw header received to recalculate signature (but verifying  lua table equivalent of that header does not have any other fields) . I will be using OpenResty 1.19 soon for my internal app. Will definitely lookout for any incompatibilities between (1.17.x and 1.19.x ) and submit PR to maintain compatibility if any discrepancies are found.

**Comment by spacewander** [comment]
Don't be panic!
I should clarify that even the signatures are different, they both can be verified by different OpenResty versions. Because during verification, the signature will be decoded to get the payload, and then re-encoded payload to get an expected signature. So even the encoded result of `cjson` (string) are different, the decoded result (Lua table) are the same.

**Comment by spacewander** [comment]
The original title is misleading. What I want to mean is the output of `jwt.sign`, which is token but not signature.

**Comment by vinayakhulawale** [comment]
just to close loop on this - I was able to verify token issued between 1.17.x and 1.19.3 versions are compatible in my real world test!
