### ISSUE TITLE
jwt.lua:494: attempt to index field 'ALGOS' (a nil value)

### ISSUE THREAD

**Issue by langhf** [cdbattags/lua-resty-jwt#8]
I just test the example code. And the error.log is showed below:

`
2018/10/09 20:49:16 [error] 13811#0: *251 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/jwt.lua:494: attempt to index field 'ALGOS' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/lualib/resty/jwt.lua: in function 'sign'
	.../drelang/p/NginxLuaKF/SmartLock/lua/api/v1/jwt/login.lua:21: in function <.../drelang/p/NginxLuaKF/SmartLock/lua/api/v1/jwt/login.lua:1>, client: 127.0.0.1, server: , request: "GET /login HTTP/1.1", host: "localhost:8001"
`

Is there is a bug in lua-resty-jwt or lua-resty-hmac ?

**Comment by cdbattags** [comment]
First glance it looks like you maybe passed `nil` in to the "algos" option?

**Comment by langhf** [comment]
My lua code just like this:
`lua
local cjson = require "cjson"
local jwt = require "resty.jwt"
local jwt_token = jwt:sign(
    "lua-resty-jwt",
    {
        header={typ="JWT", alg="HS256"},
        payload={foo="bar"}
    }
)
ngx.say(jwt_token)
`

**Comment by cdbattags** [comment]
@langhf, did you ever get this figured out?

**Comment by langhf** [comment]
No, I can not solve that problem. And I switched to lua-jwt.

**Comment by cdbattags** [comment]
So this could be an issue with your dynamic linking on whatever machine you're using. The "vendor" / "3rd party" lib we use dips down into C foreign function interface for hashes:

[hmac.lua line 87](https://github.com/cdbattags/lua-resty-jwt/blob/master/vendor/resty/hmac.lua#L87)

You could make sure those EVP functions exist as a first step.
